<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Main</title>
</head>
<body>
<h1 align="center">Інтернет-магазин по продажу комплектуючим для комп'ютера</h1><hr/>
<div style="text-align: center;"><button type="button"><a href=/product>Продукти</a></button>
<button type="button"><a href=/product>Клієнти</a></button>
<button type="button"><a href=/product>Замовлення</a></button>
<button type="button"><a href=/product>Постачальники</a></button>
<button type="button"><a href=/product>Налаштування</a></button></div>
</body>
</html>




<style type="text/css">
    body {background-color: gray;}
</style>